Ingredient.create(name: "lemon")
Ingredient.create(name: "ice")
Ingredient.create(name: "mint leaves")
Ingredient.create(name: "cachaca")
Ingredient.create(name: "tonic")
Ingredient.create(name: "gin")
Ingredient.create(name: "rhum")
